import type { DetailV1, SnapshotV1 } from "../../src/dashboard-contract.js";

const tokens = { reported: { reportedInput: { value: 12, source: "provider_reported", observedAt: "2026-08-20T12:00:00.000Z" }, reportedOutput: { value: 4, source: "provider_reported", observedAt: "2026-08-20T12:00:00.000Z" }, reportedCachedInput: { value: null, source: "provider_reported", observedAt: null } }, estimated: { estimatedInput: { value: 3, source: "relay_estimated", observedAt: "2026-08-20T12:00:00.000Z", method: "fixture" }, estimatedOutput: { value: 2, source: "relay_estimated", observedAt: "2026-08-20T12:00:00.000Z", method: "fixture" } } } as const;
const spend = { providerPublishedReported: { amountMicrousd: 1000000, priceSource: "provider_published", tokenBasis: "reported", source: "provider_reported", observedAt: "2026-08-20T12:00:00.000Z" }, providerPublishedEstimated: { amountMicrousd: 2000000, priceSource: "provider_published", tokenBasis: "estimated", source: "relay_estimated", observedAt: "2026-08-20T12:00:00.000Z" }, referenceReported: { amountMicrousd: 3000000, priceSource: "reference", tokenBasis: "reported", source: "provider_reported", observedAt: "2026-08-20T12:00:00.000Z" }, referenceEstimated: { amountMicrousd: null, priceSource: "reference", tokenBasis: "estimated", source: "unknown", observedAt: null }, unpricedRequests: 1 } as const;
const summary = { requests: 2, attempts: 3, served: 2, errored: 0, cancelled: 0, successRate: 1, tokens, spend, avgLatencyMs: 20, p95LatencyMs: 25, avgCommitMs: null } as const;
const dimensionSummary = { requests: 2, attempts: 3, served: 2, errored: 0, cancelled: 0, successRate: 1, tokens, spend, avgLatencyMs: 20, avgCommitMs: null } as const;
const request = { requestId: "request_0000000001", occurredAt: "2026-08-20T12:00:00.000Z", client: "cli", attribution: "relay_held", outcome: "success", failureKind: null, attemptCount: 2, latencyMs: 20, commitMs: null, provider: "openai", model: "gpt-test", credentialId: "openai#primary", tokens, spend, repairIncluded: true } as const;
export const snapshot = {
  schema: "dashboard.snapshot.v1", relayVersion: "test", window: "24h", includeRepair: true, attribution: "all", attributionPolicy: "unknown", generatedAt: "2026-08-20T12:00:00.000Z", asOf: "2026-08-20T12:00:00.000Z", from: "2026-08-19T12:00:00.000Z", to: "2026-08-20T12:00:00.000Z", retentionFrom: null, retentionTo: null,
  panelCoverage: ["summary", "request_timeline", "token_timeline", "spend", "provider", "model", "client", "credential", "latency", "commit", "errors", "recent", "quotas", "cooldowns"].map((panel) => ({ panel, state: panel === "quotas" || panel === "cooldowns" ? "unavailable" : "complete", reason: panel === "quotas" || panel === "cooldowns" ? "upstream_unavailable" : null, provenance: panel === "quotas" || panel === "cooldowns" ? ["unknown"] : ["relay_observed"], observedAt: panel === "quotas" || panel === "cooldowns" ? null : "2026-08-20T12:00:00.000Z" })), summary,
  buckets: [{ from: "2026-08-20T11:00:00.000Z", to: "2026-08-20T12:00:00.000Z", ...summary }], providers: [{ dimension: "provider", provider: "openai", ...dimensionSummary, coverage: "complete" }], models: [{ dimension: "model", provider: "openai", model: "gpt-test", ...dimensionSummary, coverage: "complete" }], clients: [{ dimension: "client", client: "cli", ...dimensionSummary, coverage: "complete" }], credentials: [{ dimension: "credential", provider: "openai", credentialId: "openai#primary", label: "primary", ...dimensionSummary, coverage: "complete" }], errors: [], quotas: [{ credentialId: "openai#primary", label: "primary", provider: "openai", deployment: null, axis: "requests", period: "minute", limit: 10, remaining: 5, localUsed: null, resetsAt: null, observedAt: null, limitBasis: "configured", remainingBasis: "derived_configured", localUsedBasis: null }], cooldowns: [], recentRequests: [request],
} as unknown as SnapshotV1;
export const detail = { schema: "dashboard.detail.v1", request, attempts: [{ attemptId: "attempt-1", role: "serve", startedAt: "2026-08-20T12:00:00.000Z", endedAt: "2026-08-20T12:00:00.000Z", status: "success", latencyMs: 20, commitMs: null, provider: "openai", model: "gpt-test", credentialId: "openai#primary", failureKind: null, tokens, spend }, { attemptId: "attempt-2", role: "repair", startedAt: "2026-08-20T12:00:00.000Z", endedAt: null, status: "unknown", latencyMs: null, commitMs: null, provider: "repairer", model: null, credentialId: null, failureKind: null, tokens: null, spend: null }], panelCoverage: [{ panel: "recent", state: "partial", reason: "projection_lag", provenance: ["unknown"], observedAt: null }] } as unknown as DetailV1;
