import { relayStatePath } from "./state-paths.js";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { homedir, tmpdir } from "node:os";

/**
 * The `PreToolUse(Agent)` hook that makes `offload on` mean something on a host whose traffic
 * never reaches this relay.
 *
 * ## Why a hook at all
 *
 * `routing.subagents` reroutes a subagent by answering its HTTP request differently. That requires
 * the request to arrive. In a Claude Desktop session it does not (see `src/host-routing.ts`), so
 * the switch reports ON and nothing changes — the failure this exists to close.
 *
 * ## What a hook can and cannot do — verified against the hooks reference, 2026-08-07
 *
 * It CANNOT redirect the subagent. The subagent is served by the same Claude Code process over the
 * same connection with the same pinned base URL, so no hook output changes where its tokens are
 * spent. `PreToolUse` can rewrite tool arguments via `updatedInput`, but rewriting the prompt to
 * carry an `@relay:` directive just sends that line to Anthropic as literal text, and rewriting
 * `model` picks a different Anthropic model. `SubagentStart` is context-only by specification —
 * no blocking, no model or endpoint control.
 *
 * So this is a FORCING FUNCTION, not a redirect: it denies the `Agent` call and hands back the
 * command that does reach the offload target. The deny is enforced; that the agent then runs the
 * command is not. Describe it that way — overselling it is how a nudge gets mistaken for a
 * guarantee and quota gets spent believing otherwise.
 *
 * ## Fail open, always
 *
 * Every failure path in the generated script allows the call. A hook that denied subagents because
 * the proxy was down would convert one unavailable optional lane into "no subagent works at all" —
 * the same reasoning that makes an unset `${ENV}` disable one provider instead of aborting startup.
 */

/** Marker filename. Identifies OUR entry in a settings file that may hold the user's own hooks. */
export const AGENT_HOOK_FILENAME = "llm-relay-agent-offload.mjs";

export interface ClaudeHookPaths {
  /** `~/.claude/settings.json` — the harness config this appends to. */
  settings: string;
  /** Where the generated hook script lives. Under the relay's own directory, not the harness's. */
  script: string;
}

export function claudeHookPaths(home = homedir()): ClaudeHookPaths {
  // ⚠ Under vitest, never touch the developer's real hook paths.
  // The settings path is the harness config; the script path is under the relay directory.
  // Tests pass an explicit `home` to redirect both.
  if (process.env.VITEST && home === homedir()) {
    const vitestHome = join(tmpdir(), "llm-relay-vitest");
    return {
      settings: join(vitestHome, ".claude", "settings.json"),
      script: join(vitestHome, "hooks", AGENT_HOOK_FILENAME),
    };
  }
  return {
    settings: join(home, ".claude", "settings.json"),
    // ⚠ Only the DEFAULT home resolves through the shared state policy. An explicitly passed
    // `home` keeps its literal `<home>/.llm-relay/hooks/` meaning, because that parameter is the
    // redirect seam callers and tests use — routing it through XDG would make an explicit home
    // silently not the home.
    script: home === homedir()
      ? join(relayStatePath("config", ["hooks"]), AGENT_HOOK_FILENAME)
      : join(home, ".llm-relay", "hooks", AGENT_HOOK_FILENAME),
  };
}

/**
 * The hook script, generated rather than shipped as a package file so it carries this install's
 * own interpreter and CLI path with no runtime resolution.
 *
 * ⚠ It shells out to `llm-relay dispatch --next-command` instead of talking to `/dispatch` and
 * rendering the command itself. That costs a process start per Agent call (not a hot path) and
 * buys the one thing worth paying for: a single implementation of the shell-quoting rules. A
 * second copy here would be the copy that drifts, and a drifted quoter renders a command line
 * whose task text can break out into extra shell words.
 *
 * ⚠ It runs `<node> <cli.js>`, never the installed launcher. On Windows an npm global install's
 * `llm-relay` IS a `.cmd`, and `execFileSync` refuses to execute `.cmd`/`.bat` without a shell
 * (blocked since the CVE-2024-27980 fix); a bare `.js` path is not executable either. Both fail
 * the same silent way — the hook's own fail-open catch swallows the error and every Agent call is
 * allowed, so the feature looks installed and does nothing. Naming the interpreter explicitly
 * avoids the shell entirely, which is also the safer construction.
 */
export function renderAgentHookScript(nodeBin: string, cliScript: string): string {
  return `#!/usr/bin/env node
// GENERATED by llm-relay — do not edit; \`llm-relay offload claude off\` removes it.
//
// PreToolUse(Agent): when this session's traffic does not reach llm-relay, a subagent cannot be
// rerouted to another provider — the request never arrives. Deny the call and hand back the
// command that CAN reach the configured lane.
//
// Fails OPEN on every error: a broken offload lane must never become "no subagent works".
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";

const allow = (reason) => {
  if (reason) process.stdout.write(JSON.stringify({ hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "allow", permissionDecisionReason: reason } }));
  process.exit(0);
};

try {
  // Loopback base URL => this session reaches the relay, so ordinary subagent offload works and
  // this hook must stay out of the way. Anything else (unset, or a vendor URL) => it does not.
  const base = (process.env.ANTHROPIC_BASE_URL ?? "").trim();
  const routed = /^https?:\\/\\/(localhost|127\\.\\d+\\.\\d+\\.\\d+|\\[?::1\\]?)(:|\\/|$)/i.test(base);
  if (routed) allow();

  const call = JSON.parse(readFileSync(0, "utf8")).tool_input ?? {};
  const task = typeof call.prompt === "string" ? call.prompt : "";
  if (!task) allow();

  // A prompt already pinning a target is the caller being explicit; do not second-guess it.
  if (/^\\s*@relay:/m.test(task)) allow();

  // No --tier: the Agent tool's model enum (sonnet|opus|haiku|fable) is not a ladder tier name,
  // and mapping one onto the other here would guess. Let the relay infer it from its own config.
  const args = [${JSON.stringify(cliScript)}, "dispatch", "--next-command", "-t", task, "--host", "bypassed", "--client", "claude"];
  const command = execFileSync(${JSON.stringify(nodeBin)}, args, { encoding: "utf8", timeout: 10000 }).trim();
  if (!command) allow();

  // Name the shell the line was QUOTED for. \`--next-command\` renders for the platform default
  // (PowerShell on Windows, sh elsewhere) — the same rule this mirrors. A host holding both a
  // PowerShell and a Bash tool has to be told which one, or it picks the wrong one and the
  // env-carrying prefix fails as a syntax error.
  const shell = process.platform === "win32" ? "PowerShell" : "bash";

  process.stdout.write(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason:
        "Subagent offload is ON, but this session's traffic does not reach llm-relay, so an in-process " +
        "subagent cannot be routed to another provider — it would silently spend primary quota. " +
        "Run this in " + shell + " (it is quoted for that shell), then use its output as the " +
        "subagent's result:\\n\\n" + command,
    },
  }));
  process.exit(0);
} catch (e) {
  allow();
}
`;
}

/** One `hooks.PreToolUse` entry, as Claude Code's settings schema shapes it. */
interface HookMatcher {
  matcher?: string;
  hooks?: Array<{ type?: string; command?: string }>;
}

function isOurs(entry: HookMatcher): boolean {
  return (entry.hooks ?? []).some((h) => typeof h.command === "string" && h.command.includes(AGENT_HOOK_FILENAME));
}

/**
 * Read `settings.json` as a plain object.
 *
 * A parse failure is a hard error, never a fresh `{}`. This file is the operator's harness
 * configuration — permissions, env, their own hooks — and silently replacing an unparseable one
 * would destroy all of it to install a convenience.
 */
function readSettings(path: string): Record<string, unknown> {
  if (!existsSync(path)) return {};
  const raw = readFileSync(path, "utf8");
  if (raw.trim().length === 0) return {};
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (e) {
    throw new Error(`${path} is not valid JSON (${(e as Error).message}) — fix or move it first`, { cause: e });
  }
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new Error(`${path} must contain a JSON object`);
  }
  return parsed as Record<string, unknown>;
}

function writeSettings(path: string, value: Record<string, unknown>): void {
  mkdirSync(join(path, ".."), { recursive: true });
  writeFileSync(path, JSON.stringify(value, null, 2) + "\n", "utf8");
}

/** Existing PreToolUse entries, or an empty list when the file declares none. */
function preToolUse(settings: Record<string, unknown>): HookMatcher[] {
  const hooks = settings.hooks;
  if (typeof hooks !== "object" || hooks === null || Array.isArray(hooks)) return [];
  const list = (hooks as Record<string, unknown>).PreToolUse;
  return Array.isArray(list) ? (list as HookMatcher[]) : [];
}

export interface HookChange {
  changed: boolean;
  settingsPath: string;
  scriptPath?: string;
}

/**
 * Install (or refresh) the hook.
 *
 * ⚠ APPENDS a new matcher entry; it never rewrites an existing one. Users legitimately run their
 * own `Agent` hooks — this machine has one enforcing an explicit subagent model — and Claude Code
 * runs every matching entry, so coexistence is the correct shape. Replacing the array, or editing
 * a matching entry in place, would silently delete somebody's policy.
 */
export function installAgentHook(
  nodeBin: string,
  cliScript: string,
  paths: ClaudeHookPaths = claudeHookPaths(),
): HookChange {
  mkdirSync(join(paths.script, ".."), { recursive: true });
  writeFileSync(paths.script, renderAgentHookScript(nodeBin, cliScript), "utf8");

  const settings = readSettings(paths.settings);
  const existing = preToolUse(settings);
  if (existing.some(isOurs)) {
    // Script content is refreshed above (it may carry a new relay path); the wiring is unchanged.
    return { changed: false, settingsPath: paths.settings, scriptPath: paths.script };
  }

  const entry: HookMatcher = {
    matcher: "^Agent$",
    hooks: [{ type: "command", command: `node ${JSON.stringify(paths.script)}` }],
  };
  const hooks = (typeof settings.hooks === "object" && settings.hooks !== null && !Array.isArray(settings.hooks)
    ? { ...(settings.hooks as Record<string, unknown>) }
    : {}) as Record<string, unknown>;
  hooks.PreToolUse = [...existing, entry];
  writeSettings(paths.settings, { ...settings, hooks });
  return { changed: true, settingsPath: paths.settings, scriptPath: paths.script };
}

/**
 * Remove the hook wiring. The generated script is deliberately LEFT on disk: it is inert without
 * the settings entry, it costs nothing, and deleting files outside this tool's own directory on a
 * toggle is a bigger action than the toggle asked for.
 */
export function removeAgentHook(paths: ClaudeHookPaths = claudeHookPaths()): HookChange {
  const settings = readSettings(paths.settings);
  const existing = preToolUse(settings);
  const kept = existing.filter((e) => !isOurs(e));
  if (kept.length === existing.length) return { changed: false, settingsPath: paths.settings };

  const hooks = { ...(settings.hooks as Record<string, unknown>) };
  if (kept.length > 0) hooks.PreToolUse = kept;
  else delete hooks.PreToolUse;
  // Drop an emptied `hooks` object rather than leaving `"hooks": {}` behind, so removing the hook
  // restores the file to what it looked like before rather than to something merely equivalent.
  const next = { ...settings };
  if (Object.keys(hooks).length > 0) next.hooks = hooks;
  else delete next.hooks;
  writeSettings(paths.settings, next);
  return { changed: true, settingsPath: paths.settings };
}

/** Is our hook currently wired into the harness? */
export function agentHookInstalled(paths: ClaudeHookPaths = claudeHookPaths()): boolean {
  try {
    return preToolUse(readSettings(paths.settings)).some(isOurs);
  } catch {
    // An unparseable settings file is not evidence the hook is present.
    return false;
  }
}
